LARGURA = 800
ALTURA = 600
FPS = 60
VELOCIDADE_JOGADOR = 5

# Cores
CINZA_ESCURO = (30, 30, 30)
FUNDO_BRANCO = (0, 0, 0)

# Cooldowns
TEMPO_COOLDOWN_ATAQUE_PESADO = 1500
TEMPO_COOLDOWN_ARCO = 500
TEMPO_COOLDOWN_ATAQUE_LEVE = 500

# Projétil
VELOCIDADE_PROJETIL = 10

# Configurações da Barra de HP
HP_MAXIMO = 100
HP_INICIAL = 100
POSICAO_BARRA_OFFSET_Y = -40
LARGURA_BARRA = 80
ALTURA_BARRA = 10
COR_HP_ATUAL = (0, 200, 0)
COR_HP_PERDIDO = (200, 0, 0)
BORDA_HP = True
COR_BORDA = (0, 0, 0)
TESTE_MANUAL_DANO = True

# Dano dos ataques (NOVAS CONSTANTES)
DANO_ATAQUE_LEVE = 15
DANO_ATAQUE_PESADO = 30
DANO_ARCO = 20

# Cores adicionais
PRETO = (0, 0, 0)
BRANCO = (255, 255, 255)

# Fonte
FONTE_TAMANHO = 36
CAMINHO_FONTE = None

# Estados do jogo
JOGANDO = 0
GAME_OVER = 1